### ISSUE TITLE
Remove EEO from footer

### ISSUE THREAD

**Issue by stevendshelton** [UTCWeb/utc-brandbar-html-only#1]
see https://teams.microsoft.com/l/message/19:R1LzIrNNdzGOBsebQo4bkup3fu1jPPUVoN94drPivEA1@thread.tacv2/1642770707383?tenantId=515813d9-717d-45dd-9eca-9aa19c09d6f9&groupId=3d3a4ad0-563a-4641-b001-71e32462d510&parentMessageId=1642770707383&teamName=UTC%20Web%20Team&channelName=General&createdTime=1642770707383 
![image](https://user-images.githubusercontent.com/827642/150587103-010c418f-18d7-439f-b12a-24224c8bb55a.png)
No rush. I just wanted to add this note while it was front of mind for me.

**Comment by UTCbridget** [comment]
This was done 8/17/2022.
