### ISSUE TITLE
Correct Web Requests footer link

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/utc-brandbar-html-only#8]
Change to "Web Services" and link to: 
- https://www.utc.edu/communications-and-marketing/web/web-help-center

![Screen Shot 2022-10-13 at 10 44 07 AM](https://user-images.githubusercontent.com/49878588/195629295-f27c8a9a-754b-4ad6-9811-0ea7ec31a4a4.png)

![Screen Shot 2022-10-13 at 10 47 28 AM](https://user-images.githubusercontent.com/49878588/195629898-9b8f6161-d99d-4481-a83e-e27e8a3efbe2.png)

**Comment by UTCbridget** [comment]
This has been done. Thank you!

**Comment by UTCbridget** [comment]
Now, this is done.
